DROP TABLE IF EXISTS "board" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "post" CASCADE;

CREATE TABLE "board" (
    "id" SERIAL NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "user" (
    "id" SERIAL NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "post" (
    "id" SERIAL NOT NULL,
    "author" INT NOT NULL,
    "board" INT NOT NULL,
    "content" TEXT,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("board") REFERENCES "board" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY ("author") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);